### ISSUE TITLE
Add index to public.headers.block_timestamp

### ISSUE THREAD

**Issue by hexonaut** [makerdao/vdb-mcd-transformers#179]
Apologies if this belongs in the vulcanizedb repo, but I think it's worthwhile to add an index on `public.headers.block_timestamp` in postgres. I'm performing time-based queries on the data and needed to add this index for performance reasons. This seems like a common enough use case to be added as a default.

**Comment by hexonaut** [comment]
Being added: https://github.com/makerdao/vdb-mcd-transformers/pull/203

**Comment by rmulhol** [comment]
Resolved by #203
